#!/bin/sh
# To setup git hooks run:
#   > git config core.hooksPath .git-hooks || echo 'Not in a git repo'
echo "Running .git-hooks/pre-commit..."

if git diff --name-only --cached | grep -q ":\s*go\.mod"; then
  gomodlint
  exit_code=$?
  if [ $exit_code -ne 0 ]; then
    exit $exit_code
  fi
fi

go fmt ./...
exit_code=$?
if [ $exit_code -ne 0 ]; then
  exit $exit_code
fi

go build ./...
exit_code=$?
if [ $exit_code -ne 0 ]; then
  exit $exit_code
fi

go test  ./...
exit_code=$?
if [ $exit_code -ne 0 ]; then
  exit $exit_code
fi

golangci-lint run
exit_code=$?
if [ $exit_code -ne 0 ]; then
  exit $exit_code
fi
