name: 'Serve sneat-go-backend'
description: 'Starts a backend server for sneat.app'
runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}"
      shell: bash

    - name: Install GoLang
      uses: actions/setup-go@v5
      with:
        go-version: 1.21.4
        cache: true
        cache-dependency-path: |
          ../../_actions/sneat-co/sneat-go-backend/main/go.sum


    - name: Serve sneat-go-backend
      shell: bash
      working-directory: "${{ github.action_path }}"
      run: ./scripts/serve_gae.sh & sleep 30
#      run: |
#        go version
#        pwd
#        ls
#        sh ./scripts/serve_gae.sh &
#        sleep 30
