name: 'Serve sneat-go-backend'
description: 'Starts a backend server for sneat.app'
runs:
  using: "composite"
  steps:
    - name: Install GoLang
      uses: actions/setup-go@v4
      with:
#        go-version: 1.21.4
#        check-latest: true
        cache: true

    - name: Start sneat-go-backend
      shell: bash
      run: |
        go version
        pwd
        ls
        sh ./scripts/serve_gae.sh &
        sleep 30
