name: 'Serve sneat-go-backend'
description: 'Starts a backend server for sneat.app'
runs:
  using: "composite"
  steps:
    - name: Install GoLang
      uses: actions/setup-go@v4
      with:
        go-version: 1.21.4
        cache: true
#        check-latest: true

    - run: echo "${{ github.action_path }/scripts}" >> $GITHUB_PATH
      shell: bash

    - name: Serve sneat-go-backend
      shell: bash
      run: serve_gae.sh
#      run: |
#        go version
#        pwd
#        ls
#        sh ./scripts/serve_gae.sh &
#        sleep 30
