name: 'Serve sneat-go-backend'
description: 'Starts a backend server for sneat.app'
runs:
  using: "composite"
  steps:
    - name: Install GoLang
      uses: actions/setup-go@v4
      with:
#        go-version: 1.21.4
        go-version-file: ./go.mod
        cache: true
        cache-dependency-path: |
          ./go.sum

    - run: echo "${{ github.action_path }}"
      shell: bash

    - name: Serve sneat-go-backend
      shell: bash
      working-directory: "${{ github.action_path }}"
      run: ./scripts/serve_gae.sh & sleep 30
#      run: |
#        go version
#        pwd
#        ls
#        sh ./scripts/serve_gae.sh &
#        sleep 30
