name: 'Serve sneat-go-backend' # Frontend uses this GitHub action for end-to-end testing

description: 'Starts a backend server for end-to-end testing of sneat.app in CI-build pipeline'

runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}"
      shell: bash

    - name: Install GoLang
      uses: actions/setup-go@v5
      with:
        go-version: 1.21.4
        cache: true
        cache-dependency-path: "**/*.sum"


    - name: Serve sneat-go-backend
      shell: bash
      working-directory: "${{ github.action_path }}"
      run: ./scripts/serve_gae.sh & sleep 30
