// Code generated by hero.
// source: /Users/astec/go_workspace/src/github.com/sneat-co/sneat-go-backend/debtusbot/gae_app/debtusbot/website/pages/inspector/contacts-block.html
// DO NOT EDIT!
package inspector

import (
	"bytes"
	"time"

	"github.com/shiyanhui/hero"
)

func heroContactsBlock(now time.Time, title string, contacts map[string]contactWithBalances, buffer *bytes.Buffer) {
	buffer.WriteString(`
<div>
    <div class="row">
        <h3 class="col-sm">`)
	hero.EscapeHTML(title, buffer)
	buffer.WriteString(`: `)
	hero.FormatInt(int64(len(contacts)), buffer)
	buffer.WriteString(`</h3>
    </div>

    <div class="card-columns" style="column-count: 2;">
        `)

	for _, contact := range contacts {
		heroContactCard(now, contact, buffer)
	}

	buffer.WriteString(`
    </div>
</div>


`)

}
