package facade4listus

import "strings"

var emojiKeywords = map[string][]string{
	"🍏": {"apple"},
	"🍐": {"pear", "fruit"},
	"🍊": {"orange"},
	"🍋": {"lemon"},
	"🍌": {"banana"},
	"🍉": {"watermelon"},
	"🍇": {"grapes"},
	"🍓": {"strawberry"},
	"🍈": {"melon"},
	"🍒": {"cherries"},
	"🍑": {"peach"},
	"🥭": {"mango"},
	"🍍": {"pineapple"},
	"🥥": {"coconut"},
	"🥝": {"kiwi"},
	"🍅": {"tomato"},
	"🍆": {"eggplant"},
	"🥑": {"avocado"},
	"🥦": {"broccoli"},
	"🥬": {"leafy", "greens"},
	"🥒": {"cucumber"},
	"🌶": {"chili", "pepper"},
	"🌽": {"corn"},
	"🥕": {"carrot"},
	"🧄": {"garlic"},
	"🧅": {"onion"},
	"🍠": {"sweet", "potato"},
	"🥔": {"potato"},
	"🥐": {"croissant"},
	"🥯": {"bagel"},
	"🍞": {"bread"},
	"🥖": {"baguette"},
	"🥨": {"pretzel"},
	"🧀": {"cheese"},
	"🥚": {"egg", "eggs"},
	//"🍳": {"fried", "egg"},
	"🥞": {"pancakes"},
	"🧇": {"waffle"},
	"🥓": {"bacon"},
	"🥩": {"steak"},
	"🍗": {"poultry"},
	"🍖": {"meat"},
	"🌭": {"hotdog", "hot dog", "hot dogs", "hotdogs"},
	"🍔": {"burger", "burgers"},
	"🍟": {"fries"},
	"🍕": {"pizza", "pizzas"},
	"🥪": {"sandwich", "sandwiches"},
	"🥙": {"falafel"},
	"🌮": {"taco", "tacos"},
	"🌯": {"burrito", "burritos"},
	"🥗": {"salad", "salads"},
	"🥘": {"paella"},
	"🥫": {"canned"},
	"🍝": {"spaghetti"},
	"🍜": {"noodles"},
	"🍲": {"stew"},
	"🍛": {"curry"},
	"🍣": {"sushi"},
	"🍱": {"bento"},
	"🥟": {"dumpling", "dumplings"},
	"🍤": {"shrimp"},
	"🍚": {"rice"},
	//"🍥": {"fish", "cake"},
	"🥮": {"mooncake"},
	"🍢": {"oden"},
	"🍡": {"dango"},
	"🍨": {"icecream", "ice cream"},
	//"🍧": {"shaved", "ice"},
	//"🍦": {"soft", "serve"},
	"🥧": {"pie"},
	"🧁": {"cupcake", "cupcakes"},
	"🍰": {"cake", "cakes"},
	"🎂": {"birthday cake"},
	"🍮": {"custard"},
	"🍭": {"lollipop"},
	"🍬": {"candy"},
	"🍫": {"chocolate"},
	"🍩": {"doughnut", "doughnuts"},
	"🍪": {"cookie", "cookies"},
	"🌰": {"chestnut"},
	"🥜": {"peanut"},
	"🍯": {"honey"},
	"🥛": {"milk"},
	"🍼": {"baby", "bottle"},
	"☕": {"coffee"},
	"🍵": {"tea"},
	"🍶": {"sake"},
	"🍺": {"beer"},
	"🍻": {"beers"},
	"🥂": {"clinking", "glasses"},
	"🍷": {"wine"},
	"🥃": {"whiskey"},
}

func deductListItemEmoji(text string) string {
	for emoji, keywords := range emojiKeywords {
		for _, keyword := range keywords {
			if strings.Contains(text, keyword) {
				return emoji
			}
		}
	}
	return ""
}
