// Code generated by hero.
// source: /Users/astec/go_workspace/src/github.com/sneat-co/sneat-go-backend/debtstracker/gae_app/debtstracker/website/pages/inspector/layout.html
// DO NOT EDIT!
package inspector
