package stats

const (
	USER_CREATED        = "USER_CREATED"
	USER_ACCESS_GRANTED = "USER_ACCESS_GRANTED"

	USER_EMAIL_ENTERED          = "USER_EMAIL_ENTERED"
	USER_EMAIL_CONFIRMED        = "USER_EMAIL_CONFIRMED"
	USER_PHONE_NUMBER_ENTERED   = "USER_PHONE_NUMBER_ENTERED"
	USER_PHONE_NUMBER_CONFIRMED = "USER_PHONE_NUMBER_CONFIRMED"

	COUNTERPARTY_EMAIL_ENTERED          = "COUNTERPARTY_EMAIL_ENTERED"
	COUNTERPARTY_EMAIL_CONFIRMED        = "COUNTERPARTY_EMAIL_CONFIRMED"
	COUNTERPARTY_PHONE_NUMBER_ENTERED   = "COUNTERPARTY_PHONE_NUMBER_ENTERED"
	COUNTERPARTY_PHONE_NUMBER_CONFIRMED = "COUNTERPARTY_PHONE_NUMBER_CONFIRMED"

	COUNTERPARTY_INVITED         = "COUNTERPARTY_INVITED"
	COUNTERPARTY_INVITE_ACCEPTED = "COUNTERPARTY_INVITE_ACCEPTED"

	TRANSFER_CREATED                  = "TRANSFER_CREATED"
	TRANSFER_RECEIPT_SENT_BY_EMAIL    = "TRANSFER_RECEIPT_SENT_BY_EMAIL"
	TRANSFER_RECEIPT_SENT_BY_SMS      = "TRANSFER_RECEIPT_SENT_BY_SMS"
	TRANSFER_RECEIPT_SENT_BY_TELEGRAM = "TRANSFER_RECEIPT_SENT_BY_TELEGRAM"
	TRANSFER_RECEIPT_VIEWED           = "TRANSFER_RECEIPT_VIEWED"
	TRANSFER_RECEIPT_ACCEPTED         = "TRANSFER_RECEIPT_ACCEPTED"
	TRANSFER_RECEIPT_DECLINED         = "TRANSFER_RECEIPT_DECLINED"
)
