#!/bin/sh
if git diff --name-only --cached | grep -q ":\s*go\.mod"; then
  gomodlint
  exit_code=$?
  if [ $exit_code -ne 0 ]; then
    exit $exit_code
  fi
fi
go fmt ./...
go build ./...
go test  ./...
golangci-lint run
