name: Go CI

on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+' # Push events to matching v*, i.e. v20.15.10
    paths:
      - '.github/workflows/**.yml'
      - 'src/**'
      - 'go.*'
      - '*.go'
  pull_request:
    branches:
      - '**'
    paths:
      - '.github/workflows/**.yml'
      - 'src/**'
      - 'go.*'
      - '*.go'

jobs:

  strongo_workflow:
    permissions:
      contents: write
    uses: strongo/go-ci-action/.github/workflows/workflow.yml@main

    secrets:
      # Why 2 GitHub tokens? Consider to use only one token or document why we need 2
      gh_token: ${{ secrets.GITHUB_TOKEN }}

      # This token is used to retrieve private repositories
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
    with:
      disable-version-bumping: false
